version: '3'
services:
  postgres:
    image: postgres
    container_name: rust_diesel
    environment:
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "postgres-data:/var/lib/postgres/:delegated"
      - "./docker/postgres/init:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
volumes:
  postgres-data:
    driver: local
